version: '3.8'

services:
  db:
    image: postgres:16
    container_name: witch_qa_familiar_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: wqaf
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  api:
    build: ./backend
    container_name: witch_qa_familiar_api
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/wqaf
    depends_on:
      - db
    # ports:
    #   - "5000:5000"
    
  client:
    build: ./frontend
    container_name: witch_qa_familiar_client
    ports:
      - "80:80"

volumes:
  db_data:
