version: '3.8'

services:
  db:
    image: postgres:16
    container_name: witch_qa_familiar_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  backend:
    build: ./backend
    container_name: witch_qa_familiar_back
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    ports:
      - "5000:5000"
    
  frontend:
    build: ./frontend
    container_name: witch_qa_familiar_front
    ports:
      - "80:80"

volumes:
  db_data:
